CREATE DATABASE SGVA;
USE SGVA;

CREATE TABLE Empresa(
    codigo_Empresa INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    nombre_Empresa VARCHAR(45) NOT NULL
);

CREATE TABLE Trazabilidad(
    Id_empresa INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
	Nombre_empresa VARCHAR(45) NOT NULL,
    Encargado VARCHAR(45) NOT NULL,
    Fecha_inicio VARCHAR(45) NOT NULL,
    Fecha_fin VARCHAR(45) NOT NULL,
    Telefono VARCHAR(45) NOT NULL,
    Correo VARCHAR(45) NOT NULL,
    Estado VARCHAR(45) NOT NULL,
    Fecha_cierre VARCHAR(45) NOT NULL
);